import { CardDef } from "../types/CardTypes";

export const CARDS: CardDef[] = [
  // ── TIER 1 — payout only, NO +action ────────────────────────────────────────
  {
    id: "lucky-seven",
    tier: 1,
    name: "Lucky Seven",
    description: "At least one 7",
    payoutMult: 0.05,
    pattern: { type: "ANY_DIGIT_AT_LEAST", params: { digit: 7, count: 1 } },
  },
  {
    id: "lucky-one",
    tier: 1,
    name: "Lucky One",
    description: "At least one 1",
    payoutMult: 0.05,
    pattern: { type: "ANY_DIGIT_AT_LEAST", params: { digit: 1, count: 1 } },
  },
  {
    id: "twin",
    tier: 1,
    name: "Twin",
    description: "Two equal adjacent",
    payoutMult: 0.10,
    pattern: { type: "ADJACENT_EQUAL", params: { length: 2 } },
  },
  {
    id: "high-spot",
    tier: 1,
    name: "High Spot",
    description: "An 8 or 9 anywhere",
    payoutMult: 0.05,
    pattern: { type: "ANY_OF_SET", params: { digits: [8, 9], count: 1 } },
  },
  {
    id: "low-spot",
    tier: 1,
    name: "Low Spot",
    description: "A 1 or 2 anywhere",
    payoutMult: 0.05,
    pattern: { type: "ANY_OF_SET", params: { digits: [1, 2], count: 1 } },
  },
  {
    id: "odd-pair",
    tier: 1,
    name: "Odd Pair",
    description: "Two odd adjacent",
    payoutMult: 0.10,
    pattern: { type: "ADJACENT_PARITY", params: { parity: "odd" } },
  },
  {
    id: "even-pair",
    tier: 1,
    name: "Even Pair",
    description: "Two even adjacent",
    payoutMult: 0.10,
    pattern: { type: "ADJACENT_PARITY", params: { parity: "even" } },
  },
  {
    id: "edge-match",
    tier: 1,
    name: "Edge Match",
    description: "First = Last digit",
    payoutMult: 0.15,
    pattern: { type: "EDGE_MATCH", params: {} },
  },

  // ── TIER 2 — payout + 1 action ───────────────────────────────────────────────
  {
    id: "teeth",
    tier: 2,
    name: "Teeth",
    description: "1 _ _ _ _ _ 1",
    payoutMult: 0.35,
    pattern: { type: "MASK_MATCH", params: { mask: "1_____1" } },
  },
  {
    id: "triple-run",
    tier: 2,
    name: "Triple Run",
    description: "Three equal adjacent",
    payoutMult: 0.45,
    pattern: { type: "ADJACENT_EQUAL", params: { length: 3 } },
  },
  {
    id: "lucky-sandwich",
    tier: 2,
    name: "Lucky Sandwich",
    description: "7 _ 7 anywhere",
    payoutMult: 0.40,
    pattern: { type: "MASK_MATCH", params: { mask: "7_7" } },
  },
  {
    id: "two-pairs",
    tier: 2,
    name: "Two Pairs",
    description: "aabb or abba in 4",
    payoutMult: 0.55,
    pattern: { type: "TWO_PAIRS", params: {} },
  },
  {
    id: "high-trio",
    tier: 2,
    name: "High Trio",
    description: "Three digits \u2265 7",
    payoutMult: 0.35,
    pattern: { type: "COUNT_CONDITION", params: { minDigit: 7, count: 3 } },
  },
  {
    id: "low-trio",
    tier: 2,
    name: "Low Trio",
    description: "Three digits \u2264 3",
    payoutMult: 0.35,
    pattern: { type: "COUNT_CONDITION", params: { maxDigit: 3, count: 3 } },
  },
  {
    id: "mini-stairs",
    tier: 2,
    name: "Mini Stairs",
    description: "123 or 321 adjacent",
    payoutMult: 0.60,
    pattern: { type: "RUN_SEQUENCE", params: { length: 3 } },
  },

  // ── TIER 3 — payout + 1 action ───────────────────────────────────────────────
  {
    id: "big-luck",
    tier: 3,
    name: "Big Luck",
    description: "7 7 7 adjacent",
    payoutMult: 1.50,
    pattern: { type: "EXACT_RUN", params: { digit: 7, length: 3 } },
  },
  {
    id: "four-of-a-kind",
    tier: 3,
    name: "Four of a Kind",
    description: "Four equal adjacent",
    payoutMult: 2.00,
    pattern: { type: "ADJACENT_EQUAL", params: { length: 4 } },
  },
  {
    id: "mirror",
    tier: 3,
    name: "Mirror",
    description: "abcxcba palindrome",
    payoutMult: 2.50,
    pattern: { type: "PALINDROME_7", params: {} },
  },
  {
    id: "rainbow",
    tier: 3,
    name: "Rainbow",
    description: "All 7 digits different",
    payoutMult: 2.20,
    pattern: { type: "ALL_DISTINCT_7", params: {} },
  },

  // ── TIER 4 — payout + 1 action ───────────────────────────────────────────────
  {
    id: "seven-heaven",
    tier: 4,
    name: "Seven Heaven",
    description: "7 7 7 7 7 7 7",
    payoutMult: 25.00,
    pattern: { type: "EXACT_RUN", params: { digit: 7, length: 7 } },
  },
];
